Make log print in stdout

diff --git a/.github/workflows/slow_test.yml b/.github/workflows/slow_test.yml
--- a/.github/workflows/slow_test.yml
+++ b/.github/workflows/slow_test.yml
@@ -77,7 +77,11 @@ jobs:
 
       - name: Collect infinity release output
         if: ${{ !cancelled()  && failure() }} # always run this step even if previous steps failed
-        run: (cat release.log 2>/dev/null; cat /var/infinity/log/infinity.log 2>/dev/null) || true
+        run: |
+          if [ ! -f /var/infinity/log/infinity.log ]; then
+            echo "Error: /var/infinity/log/infinity.log not found"
+          fi
+          (cat release.log 2>/dev/null; cat /var/infinity/log/infinity.log 2>/dev/null) || true
 
       - name: Prepare restart test data
         if: ${{ !cancelled() && !failure() }}
