Fix.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -60,17 +60,18 @@ jobs:
         if: ${{ !cancelled() && !failure() }}
         run: sudo docker exec ${BUILDER_CONTAINER} bash -c "git config --global safe.directory \"*\" && cd /infinity && rm -fr cmake-build-debug && mkdir -p cmake-build-debug && cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_JOB_POOLS:STRING=link=8 -S /infinity -B /infinity/cmake-build-debug && cmake --build /infinity/cmake-build-debug --target infinity test_main"
 
-      - name: Unit test debug version
-        if: ${{ !cancelled() && !failure() }}
-        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "mkdir -p /var/infinity && cd /infinity/ && ASAN_OPTIONS=detect_leaks=0 cmake-build-debug/src/test_main > unittest_debug.log 2>&1"
-
-      - name: Collect infinity unit test debug output
-        if: ${{ !cancelled() }}
-        run: cat unittest_debug.log 2>/dev/null || true
-
       - name: Install pysdk
         if: ${{ !cancelled() && !failure() }}
         run: sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && pip3 uninstall -y infinity-sdk && pip3 install . -v --config-settings=cmake.build-type='Debug' --config-settings=build-dir='cmake-build-debug'"
+
+      - name: Run restart test
+        if: ${{ !cancelled() && !failure() }}
+        run : sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && pip3 install -r python/restart_test/requirements.txt && LD_PRELOAD=/usr/local/lib/clang/18/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so ASAN_OPTIONS=detect_leaks=0 python3 tools/run_restart_test.py --infinity_path=cmake-build-debug/src/infinity"
+
+      - name: Collect restart test output
+        if: ${{ !cancelled() }} # always run this step even if previous steps failed
+        # find all log file like [debug.log.*] in directory, and cat to stdout
+        run: find . -name "restart_test.log.*" -exec cat {} \;
 
       - name: Start infinity debug version
         if: ${{ !cancelled() && !failure() }}
@@ -98,14 +99,13 @@ jobs:
         # GitHub Actions interprets output lines starting with "Error" as error messages, and it automatically sets the step status to failed when such lines are detected.
         run: cat debug.log 2>/dev/null || true
 
-      - name: Run restart test
+      - name: Unit test debug version
         if: ${{ !cancelled() && !failure() }}
-        run : sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && pip3 install -r python/restart_test/requirements.txt && python3 tools/run_restart_test.py --infinity_path=cmake-build-debug/src/infinity"
+        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "mkdir -p /var/infinity && cd /infinity/ && ASAN_OPTIONS=detect_leaks=0 cmake-build-debug/src/test_main > unittest_debug.log 2>&1"
 
-      - name: Collect restart test output
-        if: ${{ !cancelled() }} # always run this step even if previous steps failed
-        # find all log file like [debug.log.*] in directory, and cat to stdout
-        run: find . -name "restart_test.log.*" -exec cat {} \;
+      - name: Collect infinity unit test debug output
+        if: ${{ !cancelled() }}
+        run: cat unittest_debug.log 2>/dev/null || true
 
       - name: Destroy builder container
         if: always()  # always run this step even if previous steps failed
@@ -154,17 +154,18 @@ jobs:
         if: ${{ !cancelled() && !failure() }}
         run: sudo docker exec ${BUILDER_CONTAINER} bash -c "git config --global safe.directory \"*\" && cd /infinity && rm -fr cmake-build-release && mkdir -p cmake-build-release && cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_JOB_POOLS:STRING=link=8 -S /infinity -B /infinity/cmake-build-release && cmake --build /infinity/cmake-build-release --target infinity test_main knn_import_benchmark knn_query_benchmark"
 
-      - name: Unit test release version
-        if: ${{ !cancelled() && !failure() }}
-        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "mkdir -p /var/infinity && cd /infinity/ && cmake-build-release/src/test_main > unittest_release.log 2>&1"
-      
-      - name: Collect infinity unit test release output
-        if: ${{ !cancelled() }}
-        run: cat unittest_release.log 2>/dev/null || true
-
       - name: Install pysdk for Python 3.10
         if: ${{ !cancelled() && !failure() }}
         run: sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && pip3 uninstall -y infinity-sdk && pip3 install . -v --config-settings=cmake.build-type='RelWithDebInfo' --config-settings=build-dir='cmake-build-release'"
+    
+      - name: Run restart test
+        if: ${{ !cancelled() && !failure() }}
+        run : sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && pip3 install -r python/restart_test/requirements.txt && python3 tools/run_restart_test.py --infinity_path=cmake-build-release/src/infinity"
+
+      - name: Collect restart test output
+        if: ${{ !cancelled() }} # always run this step even if previous steps failed
+        # find all log file like [debug.log.*] in directory, and cat to stdout
+        run: find . -name "restart_test.log.*" -exec cat {} \;
 
       - name: Test embedded infinity for Python 3.10
         if: ${{ !cancelled() && !failure() }}
@@ -195,15 +196,14 @@ jobs:
         if: ${{ !cancelled() }} # always run this step even if previous steps failed
         # GitHub Actions interprets output lines starting with "Error" as error messages, and it automatically sets the step status to failed when such lines are detected. 
         run: cat release.log 2>/dev/null || true
-
-      - name: Run restart test
+    
+      - name: Unit test release version
         if: ${{ !cancelled() && !failure() }}
-        run : sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && pip3 install -r python/restart_test/requirements.txt && python3 tools/run_restart_test.py --infinity_path=cmake-build-release/src/infinity"
-
-      - name: Collect restart test output
-        if: ${{ !cancelled() }} # always run this step even if previous steps failed
-        # find all log file like [debug.log.*] in directory, and cat to stdout
-        run: find . -name "restart_test.log.*" -exec cat {} \;
+        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "mkdir -p /var/infinity && cd /infinity/ && cmake-build-release/src/test_main > unittest_release.log 2>&1"
+      
+      - name: Collect infinity unit test release output
+        if: ${{ !cancelled() }}
+        run: cat unittest_release.log 2>/dev/null || true
 
       - name: Prepare sift dataset
         if: ${{ !cancelled() && !failure() }}
