Upgrade to clang-20 & use libstdc++-15 (#2858)
### What problem does this PR solve?

1. Upgrade to clang-20
2. Use libstdc++
3. Fix some compile error
4. Use `<stacktrace>`
5. Use module partition

### Type of change

- [x] New Feature (non-breaking change which adds functionality)
- [x] Documentation Update
- [x] Refactoring
- [x] Test cases

Signed-off-by: noob <yixiao121314@outlook.com>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -4,6 +4,7 @@ on:
   push:
     branches:
       - 'main'
+      - 'clang-20'
       - '*.*.*'
     paths-ignore:
       - 'docs/**'
@@ -76,18 +77,18 @@ jobs:
       - name: Install pysdk
         if: ${{ !cancelled() && !failure() }}
         run: sudo docker exec ${BUILDER_CONTAINER} bash -c "rm -rf /root/.config/pip/pip.conf && cd /infinity/ && pip3 uninstall -y infinity-sdk && pip3 install python/infinity_sdk -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host tuna.tsinghua.edu.cn"
-#      - name: Run cluster test
-#        if: ${{ !cancelled() && !failure() }}
-#        id: run_cluster_test
-#        run: |
-#          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && rm -fr /var/infinity && python3 tools/run_cluster_test.py --infinity_path=cmake-build-debug/src/infinity"
-#
-#      - name: Collect cluster test output
-#        if: ${{ !cancelled() }}
-#        run: |
-#          failure="${{ steps.run_cluster_test.outcome == 'failure'}}"
-#          sudo python3 scripts/collect_cluster_log.py --executable_path=cmake-build-debug/src/infinity --log_dir=/var/infinity/ --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure}
-#
+      #      - name: Run cluster test
+      #        if: ${{ !cancelled() && !failure() }}
+      #        id: run_cluster_test
+      #        run: |
+      #          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && rm -fr /var/infinity && python3 tools/run_cluster_test.py --infinity_path=cmake-build-debug/src/infinity"
+      #
+      #      - name: Collect cluster test output
+      #        if: ${{ !cancelled() }}
+      #        run: |
+      #          failure="${{ steps.run_cluster_test.outcome == 'failure'}}"
+      #          sudo python3 scripts/collect_cluster_log.py --executable_path=cmake-build-debug/src/infinity --log_dir=/var/infinity/ --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure}
+      #
       - name: Prepare restart test data
         if: ${{ !cancelled() && !failure() }}
         run: |
@@ -97,44 +98,44 @@ jobs:
       - name: Run restart test
         if: ${{ !cancelled() && !failure() }}
         id: run_restart_test
-        run : sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && python3 tools/run_restart_test.py --infinity_path=cmake-build-debug/src/infinity"
+        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && python3 tools/run_restart_test.py --infinity_path=cmake-build-debug/src/infinity"
 
       - name: Collect restart test output
         if: ${{ !cancelled() }} # always run this step even if previous steps failed
         run: |
           failure="${{ steps.run_restart_test.outcome == 'failure'}}"
           sudo python3 scripts/collect_restart_log.py --executable_path=cmake-build-debug/src/infinity --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure}
-#
-#      - name: Start infinity debug version with minio
-#        if: ${{ !cancelled() && !failure() }}
-#        run: |
-#          # Run a command in the background
-#          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && rm -fr /var/infinity && cmake-build-debug/src/infinity --config=conf/pytest_parallel_infinity_minio.toml > vfs_debug.log 2> vfs_debug_error.log" &
-#
-#      - name: Run pysdk remote infinity & parallel & http_api & sqllogic test debug version
-#        if: ${{ !cancelled() && !failure() }}
-#        id: run_tests_debug_minio
-#        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && LD_PRELOAD=/usr/local/lib/clang/18/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so ASAN_OPTIONS=detect_leaks=0 python3 tools/run_pytest_parallel.py" && sleep 1s
-#
-#      - name: Stop infinity pysdk & http_api & sqllogictest debug
-#        if: ${{ !cancelled() }}
-#        id: stop_tests_debug_minio
-#        run: |
-#          sudo chmod +x scripts/timeout_kill.sh
-#          pids=$(sudo docker exec ${BUILDER_CONTAINER} pgrep -f cmake-build-debug/src/infinity | xargs echo)
-#          sudo docker exec ${BUILDER_CONTAINER} bash -c "/infinity/scripts/timeout_kill.sh 15 ${pids}"
-#          if [ $? -ne 0 ]; then
-#            echo "Failed to kill infinity debug version"
-#            exit 1
-#          fi
-#
-#      - name: Collect infinity debug output
-#        if: ${{ !cancelled() }}
-#        # GitHub Actions interprets output lines starting with "Error" as error messages, and it automatically sets the step status to failed when such lines are detected.
-#        run: |
-#          failure="${{ steps.run_tests_debug_minio.outcome == 'failure' || steps.stop_tests_debug_minio.outcome == 'failure' }}"
-#          sudo python3 scripts/collect_log.py --log_path=/var/infinity/log/infinity.log --stdout_path=vfs_debug.log --stderror_path=vfs_debug_error.log --executable_path=cmake-build-debug/src/infinity --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure}
-#
+      #
+      #      - name: Start infinity debug version with minio
+      #        if: ${{ !cancelled() && !failure() }}
+      #        run: |
+      #          # Run a command in the background
+      #          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && rm -fr /var/infinity && cmake-build-debug/src/infinity --config=conf/pytest_parallel_infinity_minio.toml > vfs_debug.log 2> vfs_debug_error.log" &
+      #
+      #      - name: Run pysdk remote infinity & parallel & http_api & sqllogic test debug version
+      #        if: ${{ !cancelled() && !failure() }}
+      #        id: run_tests_debug_minio
+      #        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && LD_PRELOAD=/usr/local/lib/clang/18/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so ASAN_OPTIONS=detect_leaks=0 python3 tools/run_pytest_parallel.py" && sleep 1s
+      #
+      #      - name: Stop infinity pysdk & http_api & sqllogictest debug
+      #        if: ${{ !cancelled() }}
+      #        id: stop_tests_debug_minio
+      #        run: |
+      #          sudo chmod +x scripts/timeout_kill.sh
+      #          pids=$(sudo docker exec ${BUILDER_CONTAINER} pgrep -f cmake-build-debug/src/infinity | xargs echo)
+      #          sudo docker exec ${BUILDER_CONTAINER} bash -c "/infinity/scripts/timeout_kill.sh 15 ${pids}"
+      #          if [ $? -ne 0 ]; then
+      #            echo "Failed to kill infinity debug version"
+      #            exit 1
+      #          fi
+      #
+      #      - name: Collect infinity debug output
+      #        if: ${{ !cancelled() }}
+      #        # GitHub Actions interprets output lines starting with "Error" as error messages, and it automatically sets the step status to failed when such lines are detected.
+      #        run: |
+      #          failure="${{ steps.run_tests_debug_minio.outcome == 'failure' || steps.stop_tests_debug_minio.outcome == 'failure' }}"
+      #          sudo python3 scripts/collect_log.py --log_path=/var/infinity/log/infinity.log --stdout_path=vfs_debug.log --stderror_path=vfs_debug_error.log --executable_path=cmake-build-debug/src/infinity --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure}
+      #
       - name: Start infinity debug version
         if: ${{ !cancelled() && !failure() }}
         run: |
@@ -176,7 +177,7 @@ jobs:
 
       - name: Collect infinity unit test debug output
         if: ${{ !cancelled() && failure() }}
-        run: cat unittest_debug.log 2>/dev/null || true
+        run: tail -n 1000 unittest_debug.log 2>/dev/null || true
 
       - name: Start infinity debug version
         if: ${{ !cancelled() && !failure() }}
@@ -358,22 +359,22 @@ jobs:
       #          failure="${{ steps.run_cluster_test.outcome == 'failure'}}"
       #          sudo python3 scripts/collect_cluster_log.py --executable_path=cmake-build-release/src/infinity --log_dir=/var/infinity/ --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure}
       #
-#      - name: Prepare restart test data
-#        if: ${{ !cancelled() && !failure() }}
-#        run: |
-#          RUNNER_WORKSPACE_PREFIX=${RUNNER_WORKSPACE_PREFIX:-$HOME}
-#          echo "RUNNER_WORKSPACE_PREFIX=${RUNNER_WORKSPACE_PREFIX}" >> $GITHUB_ENV
-#
-#      - name: Run restart test
-#        if: ${{ !cancelled() && !failure() }}
-#        id: run_restart_test
-#        run : sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && pip3 install -r python/restart_test/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host tuna.tsinghua.edu.cn && python3 tools/run_restart_test.py --infinity_path=cmake-build-release/src/infinity"
-#
-#      - name: Collect restart test output
-#        if: ${{ !cancelled() }} # always run this step even if previous steps failed
-#        run: |
-#          failure="${{ steps.run_restart_test.outcome == 'failure'}}"
-#          sudo python3 scripts/collect_restart_log.py --executable_path=cmake-build-release/src/infinity --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure}
+      #      - name: Prepare restart test data
+      #        if: ${{ !cancelled() && !failure() }}
+      #        run: |
+      #          RUNNER_WORKSPACE_PREFIX=${RUNNER_WORKSPACE_PREFIX:-$HOME}
+      #          echo "RUNNER_WORKSPACE_PREFIX=${RUNNER_WORKSPACE_PREFIX}" >> $GITHUB_ENV
+      #
+      #      - name: Run restart test
+      #        if: ${{ !cancelled() && !failure() }}
+      #        id: run_restart_test
+      #        run : sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && pip3 install -r python/restart_test/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host tuna.tsinghua.edu.cn && python3 tools/run_restart_test.py --infinity_path=cmake-build-release/src/infinity"
+      #
+      #      - name: Collect restart test output
+      #        if: ${{ !cancelled() }} # always run this step even if previous steps failed
+      #        run: |
+      #          failure="${{ steps.run_restart_test.outcome == 'failure'}}"
+      #          sudo python3 scripts/collect_restart_log.py --executable_path=cmake-build-release/src/infinity --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure}
       #
       #      - name: Test embedded infinity for Python 3.10
       #        if: ${{ !cancelled() && !failure() }}
@@ -457,7 +458,7 @@ jobs:
 
       - name: Collect infinity unit test release output
         if: ${{ !cancelled() }}
-        run: cat unittest_release.log 2>/dev/null || true
+        run: tail -n 1000 unittest_release.log 2>/dev/null || true
 
       - name: Start infinity release version
         if: ${{ !cancelled() && !failure() }}
@@ -562,24 +563,24 @@ jobs:
       - name: Golden benchmark sift
         if: ${{ !cancelled() && !failure() }}
         run: |
-            if [[ -f "${RUNNER_WORKSPACE_PREFIX}/benchmark/golden_benchmark_sift_1_thread.log" ]]; then
-                echo "golden benchmark result already exists!"
-                exit 0
-            fi
-            rm -fr $PWD/db_tmp && mkdir -p $PWD/db_tmp && cat ${RUNNER_WORKSPACE_PREFIX}/benchmark/infinity_conf.toml | sed -e "s|/var/infinity|$PWD/db_tmp|g" > $PWD/db_tmp/infinity_conf.toml && \
-            ${RUNNER_WORKSPACE_PREFIX}/benchmark/knn_import_benchmark --dataset=sift --dataset_dir=$PWD/test/data --infinity_dir=$PWD/db_tmp && \
-            echo "1 50" | ${RUNNER_WORKSPACE_PREFIX}/benchmark/knn_query_benchmark sift 200 false $PWD/test/data $PWD/db_tmp | sudo tee ${RUNNER_WORKSPACE_PREFIX}/benchmark/golden_benchmark_sift_1_thread.log && \
-            echo "8 50" | ${RUNNER_WORKSPACE_PREFIX}/benchmark/knn_query_benchmark sift 200 false $PWD/test/data $PWD/db_tmp | sudo tee ${RUNNER_WORKSPACE_PREFIX}/benchmark/golden_benchmark_sift_8_threads.log
+          if [[ -f "${RUNNER_WORKSPACE_PREFIX}/benchmark/golden_benchmark_sift_1_thread.log" ]]; then
+              echo "golden benchmark result already exists!"
+              exit 0
+          fi
+          rm -fr $PWD/db_tmp && mkdir -p $PWD/db_tmp && cat ${RUNNER_WORKSPACE_PREFIX}/benchmark/infinity_conf.toml | sed -e "s|/var/infinity|$PWD/db_tmp|g" > $PWD/db_tmp/infinity_conf.toml && \
+          ${RUNNER_WORKSPACE_PREFIX}/benchmark/knn_import_benchmark --dataset=sift --dataset_dir=$PWD/test/data --infinity_dir=$PWD/db_tmp && \
+          echo "1 50" | ${RUNNER_WORKSPACE_PREFIX}/benchmark/knn_query_benchmark sift 200 false $PWD/test/data $PWD/db_tmp | sudo tee ${RUNNER_WORKSPACE_PREFIX}/benchmark/golden_benchmark_sift_1_thread.log && \
+          echo "8 50" | ${RUNNER_WORKSPACE_PREFIX}/benchmark/knn_query_benchmark sift 200 false $PWD/test/data $PWD/db_tmp | sudo tee ${RUNNER_WORKSPACE_PREFIX}/benchmark/golden_benchmark_sift_8_threads.log
 
       - name: Latest benchmark sift
         if: ${{ !cancelled() && !failure() }}
         run: |
-            rm -fr $PWD/db_tmp && mkdir -p $PWD/db_tmp && cat conf/infinity_conf.toml | sed -e "s|/var/infinity|$PWD/db_tmp|g" > $PWD/db_tmp/infinity_conf.toml && \
-            ./cmake-build-release/benchmark/local_infinity/knn_import_benchmark --dataset=sift --dataset_dir=$PWD/test/data --infinity_dir=$PWD/db_tmp --config_path=db_tmp/infinity_conf.toml && \
-            echo "1 50" | ./cmake-build-release/benchmark/local_infinity/knn_query_benchmark sift 200 false $PWD/test/data $PWD/db_tmp db_tmp/infinity_conf.toml | tee benchmark_sift_1_thread.log && \
-            echo "8 50" | ./cmake-build-release/benchmark/local_infinity/knn_query_benchmark sift 200 false $PWD/test/data $PWD/db_tmp db_tmp/infinity_conf.toml | tee benchmark_sift_8_threads.log && \
-            ./tools/ci_tools/check_benchmark_result.py ${RUNNER_WORKSPACE_PREFIX}/benchmark/golden_benchmark_sift_1_thread.log benchmark_sift_1_thread.log && \
-            ./tools/ci_tools/check_benchmark_result.py ${RUNNER_WORKSPACE_PREFIX}/benchmark/golden_benchmark_sift_8_threads.log benchmark_sift_8_threads.log
+          rm -fr $PWD/db_tmp && mkdir -p $PWD/db_tmp && cat conf/infinity_conf.toml | sed -e "s|/var/infinity|$PWD/db_tmp|g" > $PWD/db_tmp/infinity_conf.toml && \
+          ./cmake-build-release/benchmark/local_infinity/knn_import_benchmark --dataset=sift --dataset_dir=$PWD/test/data --infinity_dir=$PWD/db_tmp --config_path=db_tmp/infinity_conf.toml && \
+          echo "1 50" | ./cmake-build-release/benchmark/local_infinity/knn_query_benchmark sift 200 false $PWD/test/data $PWD/db_tmp db_tmp/infinity_conf.toml | tee benchmark_sift_1_thread.log && \
+          echo "8 50" | ./cmake-build-release/benchmark/local_infinity/knn_query_benchmark sift 200 false $PWD/test/data $PWD/db_tmp db_tmp/infinity_conf.toml | tee benchmark_sift_8_threads.log && \
+          ./tools/ci_tools/check_benchmark_result.py ${RUNNER_WORKSPACE_PREFIX}/benchmark/golden_benchmark_sift_1_thread.log benchmark_sift_1_thread.log && \
+          ./tools/ci_tools/check_benchmark_result.py ${RUNNER_WORKSPACE_PREFIX}/benchmark/golden_benchmark_sift_8_threads.log benchmark_sift_8_threads.log
 
       - name: Destroy builder container
         if: always()  # always run this step even if previous steps failed
