Test
Signed-off-by: noob <yixiao121314@outlook.com>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -21,77 +21,84 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  debug_tests_clang_format:
-    name: debug_tests_clang_format
-    # https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
-    # https://github.com/orgs/community/discussions/26261
-    if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'ci') }}
-    runs-on: [ "self-hosted", "debug" ]
-    steps:
-      - name: Check format of changed C/C++ files
-        if: ${{ !cancelled() && !failure() }}
-        run: |
-          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
-            CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} \
-              | grep -E '\.(cpp|h|hpp|cppm)$' \
-              | grep -v 'third_party/' \
-              | grep -v 'build/' \
-              | grep -v 'network/' \
-              | grep -v 'parser/' || true)
-          
-            if [ -n "$CHANGED_FILES" ]; then
-              echo "Check format of changed C/C++ files with clang-format-20"
-          
-              readarray -t files <<< "$CHANGED_FILES"
-              HAS_ERROR=0
-          
-              for file in "${files[@]}"; do
-                if [ -f "$file" ]; then
-                  echo "Checking formatting: $file"
-                  sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity; clang-format-20 $file > ${file}.formatted; diff $file ${file}.formatted 2>/dev/null"
-                  if [ $? -ne 0 ]; then
-                    echo "❌ $file needs formatting"
-                    HAS_ERROR=1
-                  else
-                    echo "✅ $file is properly formatted"
-                  fi
-                  rm -f "${file}.formatted"
-                fi
-              done
-          
-              if [ $HAS_ERROR -ne 0 ]; then
-                exit 1
-              fi
-            else
-              echo "No C++ files changed"
-            fi
-          fi
+#  debug_clang_format:
+#    name: debug_clang_format
+#    # https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
+#    # https://github.com/orgs/community/discussions/26261
+#    if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'ci') }}
+#    runs-on: [ "self-hosted", "debug" ]
+#    steps:
+#      - name: Check format of changed C/C++ files
+#        if: ${{ !cancelled() && !failure() }}
+#        run: |
+#          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
+#            CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} \
+#              | grep -E '\.(cpp|h|hpp|cppm)$' \
+#              | grep -v 'third_party/' \
+#              | grep -v 'build/' \
+#              | grep -v 'network/' \
+#              | grep -v 'parser/' || true)
+#
+#            if [ -n "$CHANGED_FILES" ]; then
+#              echo "Check format of changed C/C++ files with clang-format-20"
+#
+#              readarray -t files <<< "$CHANGED_FILES"
+#              HAS_ERROR=0
+#
+#              for file in "${files[@]}"; do
+#                if [ -f "$file" ]; then
+#                  echo "Checking formatting: $file"
+#                  sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity; clang-format-20 $file > ${file}.formatted; diff $file ${file}.formatted 2>/dev/null"
+#                  if [ $? -ne 0 ]; then
+#                    echo "❌ $file needs formatting"
+#                    HAS_ERROR=1
+#                  else
+#                    echo "✅ $file is properly formatted"
+#                  fi
+#                  rm -f "${file}.formatted"
+#                fi
+#              done
+#
+#              if [ $HAS_ERROR -ne 0 ]; then
+#                exit 1
+#              fi
+#            else
+#              echo "No C++ files changed"
+#            fi
+#          fi
 
-  debug_tests_congigure_and_build:
-    name: debug_tests_congigure_and_build
+  debug_configure_and_build:
+    name: debug_congigure_and_build
     # https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
     # https://github.com/orgs/community/discussions/26261
     if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'ci') }}
     runs-on: [ "self-hosted", "debug" ]
-    needs: debug_tests_clang_format
+#    needs: debug_clang_format
+    outputs:
+      my_variable: ${{ steps.set_var.outputs.container_name }}
     steps:
       - name: Start builder container
         if: ${{ !cancelled() && !failure() }}
         run: |
           BUILDER_CONTAINER=infinity_build_$(od -An -N4 -tx4 /dev/urandom | tr -d ' ')
+          echo "container_name=${BUILDER_CONTAINER}" >> $GITHUB_OUTPUT
           CPUS=${CPUS:-$(nproc)}
           echo "BUILDER_CONTAINER=${BUILDER_CONTAINER}" >> $GITHUB_ENV
           echo "CPUS=${CPUS}" >> $GITHUB_ENV
           TZ=${TZ:-$(readlink -f /etc/localtime | awk -F '/zoneinfo/' '{print $2}')}
-          sudo docker rm -f -v ${BUILDER_CONTAINER} && sudo docker run --privileged --cap-add=NET_ADMIN -d --name ${BUILDER_CONTAINER} -e TZ=$TZ -e CMAKE_BUILD_PARALLEL_LEVEL=${CPUS} -v $PWD:/infinity -v /var/run/docker.sock:/var/run/docker.sock --cpus ${CPUS} infiniflow/infinity_builder:ubuntu20_clang20
+          sudo docker rm -f -v ${BUILDER_CONTAINER} && sudo docker run --privileged --cap-add=NET_ADMIN -d --name ${BUILDER_CONTAINER} -e TZ=$TZ -e CMAKE_BUILD_PARALLEL_LEVEL=${CPUS} -v $PWD:/infinity --cpus ${CPUS} infiniflow/infinity_builder:ubuntu20_clang20
 
-      - name: Configure debug version
-        if: ${{ !cancelled() && !failure() }}
-        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "git config --global safe.directory \"*\" && cd /infinity && rm -fr cmake-build-debug && mkdir -p cmake-build-debug && cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_JOB_POOLS:STRING=link=8 -DCI=ON -S /infinity -B /infinity/cmake-build-debug"
-
-      - name: Build debug version
-        if: ${{ !cancelled() && !failure() }}
-        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity && cmake --build /infinity/cmake-build-debug --target infinity"
+#      - name: Configure debug version
+#        if: ${{ !cancelled() && !failure() }}
+#        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "git config --global safe.directory \"*\" && cd /infinity && rm -fr cmake-build-debug && mkdir -p cmake-build-debug && cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_JOB_POOLS:STRING=link=8 -DCI=ON -S /infinity -B /infinity/cmake-build-debug"
+#
+#      - name: Build debug version
+#        if: ${{ !cancelled() && !failure() }}
+#        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity && cmake --build /infinity/cmake-build-debug --target infinity"
+#
+#      - name: Build unit test
+#        if: ${{ !cancelled() && !failure() }}
+#        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "git config --global safe.directory \"*\" && cd /infinity && cmake --build /infinity/cmake-build-debug --target test_main"
 
       - name: Destroy builder container
         if: always()  # always run this step even if previous steps failed
@@ -99,6 +106,32 @@ jobs:
           if [ -n "${BUILDER_CONTAINER}" ]; then
             sudo docker rm -f -v ${BUILDER_CONTAINER}
           fi
+          
+
+  debug_unit_test:
+    name: debug_tests_unit_test
+    # https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
+    # https://github.com/orgs/community/discussions/26261
+    if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'ci') }}
+    runs-on: [ "self-hosted", "debug" ]
+    needs: debug_configure_and_build
+    steps:
+      - name: Get container name
+        if: ${{ !cancelled() && !failure() }}
+        run: |
+          echo "------${{ needs.debug_configure_and_build.outputs.container_name }}"
+#      - name: Unit test debug version
+#        if: ${{ !cancelled() && !failure() }}
+#        id: run_unit_test_debug
+#        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "mkdir -p /var/infinity && cd /infinity/ && ASAN_OPTIONS=detect_leaks=0 cmake-build-debug/src/test_main > unittest_debug.log 2> unittest_debug_error.log"
+#
+#      - name: Destroy builder container
+#        if: always()  # always run this step even if previous steps failed
+#        run: |
+#          if [ -n "${BUILDER_CONTAINER}" ]; then
+#            sudo docker rm -f -v ${BUILDER_CONTAINER}
+#          fi
+
 
 #  debug_tests:
 #    name: debug_tests
