Fix
Signed-off-by: noob <yixiao121314@outlook.com>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -106,37 +106,37 @@ jobs:
         run: |
           failure="${{ steps.run_restart_test.outcome == 'failure'}}"
           sudo python3 scripts/collect_restart_log.py --executable_path=cmake-build-debug/src/infinity --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure}
-      #
-      #      - name: Start infinity debug version with minio
-      #        if: ${{ !cancelled() && !failure() }}
-      #        run: |
-      #          # Run a command in the background
-      #          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && rm -fr /var/infinity && cmake-build-debug/src/infinity --config=conf/pytest_parallel_infinity_minio.toml > vfs_debug.log 2> vfs_debug_error.log" &
-      #
-      #      - name: Run pysdk remote infinity & parallel & http_api & sqllogic test debug version
-      #        if: ${{ !cancelled() && !failure() }}
-      #        id: run_tests_debug_minio
-      #        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && LD_PRELOAD=/usr/local/lib/clang/18/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so ASAN_OPTIONS=detect_leaks=0 python3 tools/run_pytest_parallel.py" && sleep 1s
-      #
-      #      - name: Stop infinity pysdk & http_api & sqllogictest debug
-      #        if: ${{ !cancelled() }}
-      #        id: stop_tests_debug_minio
-      #        run: |
-      #          sudo chmod +x scripts/timeout_kill.sh
-      #          pids=$(sudo docker exec ${BUILDER_CONTAINER} pgrep -f cmake-build-debug/src/infinity | xargs echo)
-      #          sudo docker exec ${BUILDER_CONTAINER} bash -c "/infinity/scripts/timeout_kill.sh 15 ${pids}"
-      #          if [ $? -ne 0 ]; then
-      #            echo "Failed to kill infinity debug version"
-      #            exit 1
-      #          fi
-      #
-      #      - name: Collect infinity debug output
-      #        if: ${{ !cancelled() }}
-      #        # GitHub Actions interprets output lines starting with "Error" as error messages, and it automatically sets the step status to failed when such lines are detected.
-      #        run: |
-      #          failure="${{ steps.run_tests_debug_minio.outcome == 'failure' || steps.stop_tests_debug_minio.outcome == 'failure' }}"
-      #          sudo python3 scripts/collect_log.py --log_path=/var/infinity/log/infinity.log --stdout_path=vfs_debug.log --stderror_path=vfs_debug_error.log --executable_path=cmake-build-debug/src/infinity --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure}
-      #
+#
+#      - name: Start infinity debug version with minio
+#        if: ${{ !cancelled() && !failure() }}
+#        run: |
+#          # Run a command in the background
+#          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && rm -fr /var/infinity && cmake-build-debug/src/infinity --config=conf/pytest_parallel_infinity_minio.toml > vfs_debug.log 2> vfs_debug_error.log" &
+#
+#      - name: Run pysdk remote infinity & parallel & http_api & sqllogic test debug version
+#        if: ${{ !cancelled() && !failure() }}
+#        id: run_tests_debug_minio
+#        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && LD_PRELOAD=/usr/local/lib/clang/18/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so ASAN_OPTIONS=detect_leaks=0 python3 tools/run_pytest_parallel.py" && sleep 1s
+#
+#      - name: Stop infinity pysdk & http_api & sqllogictest debug
+#        if: ${{ !cancelled() }}
+#        id: stop_tests_debug_minio
+#        run: |
+#          sudo chmod +x scripts/timeout_kill.sh
+#          pids=$(sudo docker exec ${BUILDER_CONTAINER} pgrep -f cmake-build-debug/src/infinity | xargs echo)
+#          sudo docker exec ${BUILDER_CONTAINER} bash -c "/infinity/scripts/timeout_kill.sh 15 ${pids}"
+#          if [ $? -ne 0 ]; then
+#            echo "Failed to kill infinity debug version"
+#            exit 1
+#          fi
+#
+#      - name: Collect infinity debug output
+#        if: ${{ !cancelled() }}
+#        # GitHub Actions interprets output lines starting with "Error" as error messages, and it automatically sets the step status to failed when such lines are detected.
+#        run: |
+#          failure="${{ steps.run_tests_debug_minio.outcome == 'failure' || steps.stop_tests_debug_minio.outcome == 'failure' }}"
+#          sudo python3 scripts/collect_log.py --log_path=/var/infinity/log/infinity.log --stdout_path=vfs_debug.log --stderror_path=vfs_debug_error.log --executable_path=cmake-build-debug/src/infinity --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure}
+#
       - name: Start infinity debug version
         if: ${{ !cancelled() && !failure() }}
         run: |
