Fix.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -83,7 +83,7 @@ jobs:
       - name: Stop infinity pysdk & http_api debug
         if: ${{ !cancelled() }} # always run this step even if previous steps failed
         run: |
-          sh ./timeout_kill.sh $(pidof cmake-build-debug/src/infinity) 10
+          sudo bash ${GITHUB_WORKSPACE}/scripts/timeout_kill.sh $(pidof cmake-build-debug/src/infinity) 10s
           if [ $? -ne 0 ]; then
             echo "Failed to kill infinity debug version"
             exit 1
@@ -101,12 +101,12 @@ jobs:
 
       - name: Stop infinity sqllogictest debug
         if: ${{ !cancelled() }} # always run this step even if previous steps failed
-          run: |
-            sh ./timeout_kill.sh $(pidof cmake-build-debug/src/infinity) 10
-            if [ $? -ne 0 ]; then
-              echo "Failed to kill infinity debug version"
-              exit 1
-            fi
+        run: |
+          sudo bash ${GITHUB_WORKSPACE}/scripts/timeout_kill.sh $(pidof cmake-build-debug/src/infinity) 10s
+          if [ $? -ne 0 ]; then
+            echo "Failed to kill infinity debug version"
+            exit 1
+          fi
 
       - name: Collect infinity debug output
         # GitHub Actions interprets output lines starting with "Error" as error messages, and it automatically sets the step status to failed when such lines are detected.
@@ -178,7 +178,7 @@ jobs:
       - name: Stop infinity pysdk & http_api release
         if: ${{ !cancelled() }} # always run this step even if previous steps failed
         run: |
-          sh ./timeout_kill.sh $(pidof cmake-build-release/src/infinity) 10
+          sudo bash ${GITHUB_WORKSPACE}/scripts/timeout_kill.sh $(pidof cmake-build-release/src/infinity) 10s
           if [ $? -ne 0 ]; then
             echo "Failed to kill infinity debug version"
             exit 1
@@ -196,7 +196,7 @@ jobs:
       - name: Stop infinity sqllogictest release
         if: ${{ !cancelled() }} # always run this step even if previous steps failed
         run: |
-          sh ./timeout_kill.sh $(pidof cmake-build-release/src/infinity) 10
+          sudo bash ${GITHUB_WORKSPACE}/scripts/timeout_kill.sh $(pidof cmake-build-release/src/infinity) 10s
           if [ $? -ne 0 ]; then
             echo "Failed to kill infinity debug version"
             exit 1
