Stage I
Signed-off-by: noob <yixiao121314@outlook.com>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -21,50 +21,50 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-#    code_quality_analyze:
-#      name: code_quality_analyze
-#      # https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
-#      # https://github.com/orgs/community/discussions/26261
-#      if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'ci') }}
-#      runs-on: [ "self-hosted", "debug" ]
-#      steps:
-#        - name: Check format of changed C/C++ files
-#          if: ${{ !cancelled() && !failure() }}
-#          run: |
-#            if [[ ${{ github.event_name }} == 'pull_request' ]]; then
-#              CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} \
-#                | grep -E '\.(cpp|h|hpp|cppm)$' \
-#                | grep -v 'third_party/' \
-#                | grep -v 'network/' \
-#                | grep -v 'parser/' || true)
+#  code_quality_analyze:
+#    name: code_quality_analyze
+#    # https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
+#    # https://github.com/orgs/community/discussions/26261
+#    if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'ci') }}
+#    runs-on: [ "self-hosted", "debug" ]
+#    steps:
+#      - name: Check format of changed C/C++ files
+#        if: ${{ !cancelled() && !failure() }}
+#        run: |
+#          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
+#            CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} \
+#              | grep -E '\.(cpp|h|hpp|cppm)$' \
+#              | grep -v 'third_party/' \
+#              | grep -v 'network/' \
+#              | grep -v 'parser/' || true)
 #
-#              if [ -n "$CHANGED_FILES" ]; then
-#                echo "Check format of changed C/C++ files with clang-format-20"
+#            if [ -n "$CHANGED_FILES" ]; then
+#              echo "Check format of changed C/C++ files with clang-format-20"
 #
-#                readarray -t files <<< "$CHANGED_FILES"
-#                HAS_ERROR=0
+#              readarray -t files <<< "$CHANGED_FILES"
+#              HAS_ERROR=0
 #
-#                for file in "${files[@]}"; do
-#                  if [ -f "$file" ]; then
-#                    echo "Checking formatting: $file"
-#                    sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity; clang-format-20 $file > ${file}.formatted; diff $file ${file}.formatted 2>/dev/null"
-#                    if [ $? -ne 0 ]; then
-#                      echo "❌ $file needs formatting"
-#                      HAS_ERROR=1
-#                    else
-#                      echo "✅ $file is properly formatted"
-#                    fi
-#                    rm -f "${file}.formatted"
+#              for file in "${files[@]}"; do
+#                if [ -f "$file" ]; then
+#                  echo "Checking formatting: $file"
+#                  sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity; clang-format-20 $file > ${file}.formatted; diff $file ${file}.formatted 2>/dev/null"
+#                  if [ $? -ne 0 ]; then
+#                    echo "❌ $file needs formatting"
+#                    HAS_ERROR=1
+#                  else
+#                    echo "✅ $file is properly formatted"
 #                  fi
-#                done
-#
-#                if [ $HAS_ERROR -ne 0 ]; then
-#                  exit 1
+#                  rm -f "${file}.formatted"
 #                fi
-#              else
-#                echo "No C++ files changed"
+#              done
+#
+#              if [ $HAS_ERROR -ne 0 ]; then
+#                exit 1
 #              fi
+#            else
+#              echo "No C++ files changed"
 #            fi
+#          fi
 
   debug_configure_and_build:
     name: debug_configure_and_build
@@ -73,7 +73,7 @@ jobs:
     # https://github.com/orgs/community/discussions/26261
     if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'ci') }}
     runs-on: [ "self-hosted", "debug" ]
-    #    needs: debug_clang_format
+    needs: code_quality_analyze
     outputs:
       BUILD_IP: ${{ steps.get_ip.outputs.BUILD_IP }}
       CONTAINER_NAME: ${{ steps.start.outputs.CONTAINER_NAME }}
@@ -208,7 +208,6 @@ jobs:
         if: ${{ !cancelled() && !failure() }}
         run: |
           TEST_CONTAINER_NAME=infinity_test_$(od -An -N4 -tx4 /dev/urandom | tr -d ' ')
-          echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_OUTPUT
           echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_ENV
           echo "BUILD_CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV
           TZ=${TZ:-$(readlink -f /etc/localtime | awk -F '/zoneinfo/' '{print $2}')}
@@ -306,7 +305,6 @@ jobs:
         if: ${{ !cancelled() && !failure() }}
         run: |
           TEST_CONTAINER_NAME=infinity_test_$(od -An -N4 -tx4 /dev/urandom | tr -d ' ')
-          echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_OUTPUT
           echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_ENV
           echo "BUILD_CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV
           TZ=${TZ:-$(readlink -f /etc/localtime | awk -F '/zoneinfo/' '{print $2}')}
@@ -387,7 +385,6 @@ jobs:
         if: ${{ !cancelled() && !failure() }}
         run: |
           TEST_CONTAINER_NAME=infinity_test_$(od -An -N4 -tx4 /dev/urandom | tr -d ' ')
-          echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_OUTPUT
           echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_ENV
           echo "BUILD_CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV
           TZ=${TZ:-$(readlink -f /etc/localtime | awk -F '/zoneinfo/' '{print $2}')}
@@ -480,7 +477,6 @@ jobs:
         if: ${{ !cancelled() && !failure() }}
         run: |
           TEST_CONTAINER_NAME=infinity_test_$(od -An -N4 -tx4 /dev/urandom | tr -d ' ')
-          echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_OUTPUT
           echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_ENV
           echo "BUILD_CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV
           TZ=${TZ:-$(readlink -f /etc/localtime | awk -F '/zoneinfo/' '{print $2}')}
@@ -577,7 +573,6 @@ jobs:
         if: ${{ !cancelled() && !failure() }}
         run: |
           TEST_CONTAINER_NAME=infinity_test_$(od -An -N4 -tx4 /dev/urandom | tr -d ' ')
-          echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_OUTPUT
           echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_ENV
           echo "BUILD_CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV
           TZ=${TZ:-$(readlink -f /etc/localtime | awk -F '/zoneinfo/' '{print $2}')}
@@ -676,7 +671,6 @@ jobs:
         if: ${{ !cancelled() && !failure() }}
         run: |
           TEST_CONTAINER_NAME=infinity_test_$(od -An -N4 -tx4 /dev/urandom | tr -d ' ')
-          echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_OUTPUT
           echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_ENV
           echo "BUILD_CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV
           TZ=${TZ:-$(readlink -f /etc/localtime | awk -F '/zoneinfo/' '{print $2}')}
@@ -730,7 +724,7 @@ jobs:
     # https://github.com/orgs/community/discussions/26261
     if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'ci') }}
     runs-on: [ "self-hosted", "debug" ]
-    #    needs: debug_clang_format
+    needs: code_quality_analyze
     outputs:
       BUILD_IP: ${{ steps.get_ip.outputs.BUILD_IP }}
       CONTAINER_NAME: ${{ steps.start.outputs.CONTAINER_NAME }}
@@ -759,7 +753,6 @@ jobs:
         if: ${{ !cancelled() && !failure() }}
         run: |
           BUILDER_CONTAINER=infinity_build_$(od -An -N4 -tx4 /dev/urandom | tr -d ' ')
-          echo "test=${BUILDER_CONTAINER}" >> $GITHUB_OUTPUT
           echo "CONTAINER_NAME=${BUILDER_CONTAINER}" >> $GITHUB_OUTPUT
           CPUS=${CPUS:-$(nproc)}
           echo "BUILDER_CONTAINER=${BUILDER_CONTAINER}" >> $GITHUB_ENV
@@ -874,7 +867,6 @@ jobs:
         if: ${{ !cancelled() && !failure() }}
         run: |
           TEST_CONTAINER_NAME=infinity_test_$(od -An -N4 -tx4 /dev/urandom | tr -d ' ')
-          echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_OUTPUT
           echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_ENV
           echo "BUILD_CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV
           TZ=${TZ:-$(readlink -f /etc/localtime | awk -F '/zoneinfo/' '{print $2}')}
@@ -972,7 +964,6 @@ jobs:
         if: ${{ !cancelled() && !failure() }}
         run: |
           TEST_CONTAINER_NAME=infinity_test_$(od -An -N4 -tx4 /dev/urandom | tr -d ' ')
-          echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_OUTPUT
           echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_ENV
           echo "BUILD_CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV
           TZ=${TZ:-$(readlink -f /etc/localtime | awk -F '/zoneinfo/' '{print $2}')}
@@ -1053,7 +1044,6 @@ jobs:
         if: ${{ !cancelled() && !failure() }}
         run: |
           TEST_CONTAINER_NAME=infinity_test_$(od -An -N4 -tx4 /dev/urandom | tr -d ' ')
-          echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_OUTPUT
           echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_ENV
           echo "BUILD_CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV
           TZ=${TZ:-$(readlink -f /etc/localtime | awk -F '/zoneinfo/' '{print $2}')}
@@ -1150,7 +1140,6 @@ jobs:
         if: ${{ !cancelled() && !failure() }}
         run: |
           TEST_CONTAINER_NAME=infinity_test_$(od -An -N4 -tx4 /dev/urandom | tr -d ' ')
-          echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_OUTPUT
           echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_ENV
           echo "BUILD_CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV
           TZ=${TZ:-$(readlink -f /etc/localtime | awk -F '/zoneinfo/' '{print $2}')}
@@ -1251,7 +1240,6 @@ jobs:
         if: ${{ !cancelled() && !failure() }}
         run: |
           TEST_CONTAINER_NAME=infinity_test_$(od -An -N4 -tx4 /dev/urandom | tr -d ' ')
-          echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_OUTPUT
           echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_ENV
           echo "BUILD_CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV
           TZ=${TZ:-$(readlink -f /etc/localtime | awk -F '/zoneinfo/' '{print $2}')}
@@ -1349,7 +1337,6 @@ jobs:
         if: ${{ !cancelled() && !failure() }}
         run: |
           TEST_CONTAINER_NAME=infinity_test_$(od -An -N4 -tx4 /dev/urandom | tr -d ' ')
-          echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_OUTPUT
           echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_ENV
           echo "BUILD_CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV
           TZ=${TZ:-$(readlink -f /etc/localtime | awk -F '/zoneinfo/' '{print $2}')}
@@ -1466,7 +1453,6 @@ jobs:
         if: ${{ !cancelled() && !failure() }}
         run: |
           TEST_CONTAINER_NAME=infinity_test_$(od -An -N4 -tx4 /dev/urandom | tr -d ' ')
-          echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_OUTPUT
           echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_ENV
           echo "BUILD_CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV
           TZ=${TZ:-$(readlink -f /etc/localtime | awk -F '/zoneinfo/' '{print $2}')}
@@ -1587,7 +1573,6 @@ jobs:
         if: ${{ !cancelled() && !failure() }}
         run: |
           TEST_CONTAINER_NAME=infinity_test_$(od -An -N4 -tx4 /dev/urandom | tr -d ' ')
-          echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_OUTPUT
           echo "TEST_CONTAINER_NAME=${TEST_CONTAINER_NAME}" >> $GITHUB_ENV
           echo "BUILD_CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV
           TZ=${TZ:-$(readlink -f /etc/localtime | awk -F '/zoneinfo/' '{print $2}')}
